export enum PokemonTypes {
  POKEMON_LIST_LOADING = "POKEMON_LIST_LOADING",
  POKEMON_LIST_SUCCESS = "POKEMON_LIST_SUCCESS",
  POKEMON_LIST_FAIL = "POKEMON_LIST_FAIL",
  POKEMON_SINGLE_LOADING = "POKEMON_SINGLE_LOADING",
  POKEMON_SINGLE_SUCCESS = "POKEMON_SINGLE_SUCCESS",
  POKEMON_SINGLE_FAIL = "POKEMON_SINGLE_FAIL",
}
